# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20171215_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='host',
            field=models.ManyToManyField(default=1, to='app01.Host', verbose_name='主机'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.UserType', verbose_name='类型'),
        ),
    ]
